### ISSUE TITLE
[website] Markdown renderer cannot render CommonMark markdown html

### ISSUE THREAD

**Issue by duanwilliam** [acmucsd/acm-ai-workshops#17]
(found in #16 ) Regular markdown allows for inline html, which uses strings for passing certain properties (e.g. `<font color="red">`, or `<span style="color: red">`). However, the website parses html as JSX, which uses a different syntax.

As part of the notebook conversion step, the Markdown AST or HTML AST should probably be traversed to convert "standard" HTML elements to valid JSX, by parsing properties that differ between them e.g. `color`, `style`, and `class`/`className`

There also appears to be an issue with mdx-bundler being unable to render regular strings with a forward slash in them, such as a url.

Possible fix: `mdx` supports "vanilla" markdown parsing (https://github.com/mdx-js/mdx/tree/main/packages/mdx#optionsformat) which hopefully would be able to resolve all of these various issues of markdown incompatibility. However, there are two issues that still stand:
1. `mdx-bundler` can't seem to properly handle the files when setting the markdown format to `md`
2. how should the table of contents be obtained otherwise?
    - one idea I have is to do two passes when bundling - one, for the actual bundling of the markdown, and the other, which gets the table of contents by inlining the plugin and modifying a `toc` variable in scope to get the toc for each page. however, this will require a significant refactor

**Comment by duanwilliam** [comment]
update on findings so far:
- on the bright side, using the "vanilla" markdown renderer results in the issue with links going away
- on the down side, the "vanilla" markdown renderer seems to ignore all html altogether, which messes up e.g. the handmade table of contents, or any spans for adding color

**Comment by arth-shukla** [comment]
Updates made to all nlp series notebooks:
- removed handmade toc
- reduced all header levels by 1 (only h2 to h4 remain)
- moved "Please ***Make A Copy***" below title

**Comment by duanwilliam** [comment]
migrating to pure vanilla markdown parser seems to be working so far. a new concern from using that though:
- when adding output cells to the notebooks, it may be difficult to properly link assets, images, etc. We may end up needing to basically copy the notebooks' folders into the `static` folder and then use a base URL to work around this. Subject for later discussion. With the old parser, linked assets would go into a base url of `/static/content`.
