### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by StoneT2000** [acmucsd/acm-ai-workshops#21]
There should be some simple automatic syntax highlighters out there to auto highlight the python code in these jupyter notebooks

**Comment by StoneT2000** [comment]
@duanwilliam thoughts on beginner friendliness of this? Could be a easy intro issue to our tech stack ish? Unless this repo is a bit too different.

**Comment by duanwilliam** [comment]
wait fuk i think this is a regression from changing markdown parsers. will look into it
